version: '3.4'

services:
  backend:
    image: ${DOCKER_USERNAME}/deces-backend-${EXEC_ENV}:${APP_VERSION}
    container_name: deces-backend-${EXEC_ENV}
    volumes:
      - ${BACKEND}/src:/${APP}/src/
      - ${BACKEND}/dist:/${APP}/dist/
      - ${BACKEND}/tests:/${APP}/tests/
      - ${BACKEND}/data:/${APP}/data/
      - /${APP}/node_modules
    ports:
      - ${PORT}:8080
