version: '3.4'

services:
  backend:
    image: ${DOCKER_USERNAME}/deces-backend-${EXEC_ENV}:${APP_VERSION}
    container_name: deces-backend-${EXEC_ENV}
    environment:
      - NODE_ENV=${EXEC_ENV}
      - BACKEND_PORT=${BACKEND_PORT}
      - APP=${APP}
      - APP_VERSION=${APP_VERSION}
      - APP_DNS=${APP_DNS}
      - BACKEND_PROXY_PATH=${BACKEND_PROXY_PATH}
      - BACKEND_JOB_CONCURRENCY=${BACKEND_JOB_CONCURRENCY}
      - BACKEND_CHUNK_CONCURRENCY=${BACKEND_CHUNK_CONCURRENCY}
      - BACKEND_LOG_LEVEL=${BACKEND_LOG_LEVEL}
      - BACKEND_LOG_TIMER=${BACKEND_LOG_TIMER}
      - BACKEND_TOKEN_KEY=${BACKEND_TOKEN_KEY}
      - BACKEND_TOKEN_USER=${BACKEND_TOKEN_USER}
      - BACKEND_TOKEN_PASSWORD=${BACKEND_TOKEN_PASSWORD}
      - BACKEND_TMP_MAX=${BACKEND_TMP_MAX}
      - BACKEND_TMP_DURATION=${BACKEND_TMP_DURATION}
      - BACKEND_TMP_WINDOW=${BACKEND_TMP_WINDOW}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PWD=${SMTP_PWD}
      - API_URL=${API_URL}
      - API_SSL=${API_SSL}
      - API_EMAIL=${API_EMAIL}
      - DATAGOUV_CATALOG_URL=${DATAGOUV_CATALOG_URL}
      - DATAGOUV_RESOURCES_URL=${DATAGOUV_RESOURCES_URL}
      - DATAGOUV_PROXY_PATH=${DATAGOUV_PROXY_PATH}
      - ES_URL=${ES_HOST}:${ES_PORT}
      - ES_INDEX=${ES_INDEX}
    volumes:
      - ${BACKEND}/src:/${APP}/src/
      - ${BACKEND}/dist:/${APP}/dist/
      - ${BACKEND}/tests:/${APP}/tests/
      - ${BACKEND}/data:/${APP}/data/
      - /${APP}/node_modules
    ports:
      - ${PORT}:8080
